Repository TEAM-Workit/Workit-iOS, pull requests merged in 2022-11, with the labels that each got.

#2 Chore: 프로젝트 세팅(#1)
  .gitignore
  .package.resolved
  .swiftlint.yml
  .tuist-version
  Projects/App/Plists/Info.plist
  Projects/App/Project.swift
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/Applications/Config/example.swift
  Projects/App/Sources/Applications/Supports/AppDelegate.swift
  Projects/App/Sources/Applications/Supports/SceneDelegate.swift
  Projects/App/Sources/Global/Extensions/UIViewController+.swift
  Projects/App/Sources/Global/Utils/example.swift
  Projects/App/Sources/Screens/Home/HomeReactor.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Tests/AppTests.swift
  Projects/Data/Project.swift
  Projects/Data/Resources/example.swift
  Projects/Data/Sources/example.swift
  Projects/Data/Tests/AppTests.swift
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Resources/Fonts/example.swift
  Projects/DesignSystem/Sources/UIComponents/example.swift
  Projects/DesignSystem/Tests/AppTests.swift
  Scripts/SwiftLintRunScript.sh
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/OrganizationName.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/TargetScript.swift
  Workspace.swift
Labels: ✅ chore

#6 CI: GitHub Action 설정 (#5)
  .github/workflows/SwiftLint.yml
  .github/workflows/labeler.yml
  .swiftlint.yml
Labels: ✅ chore, 🚂 CI, size/s

#11 Chore: 디자인시스템 의존성 추가 (#10)
  Projects/DesignSystem/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✅ chore, size/s

#14 Feat: InputTextField 컴포넌트 구현
  Projects/DesignSystem/Resources/Assets.xcassets/wkTextFieldXButton.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wkTextFieldXButton.imageset/Frame 59697.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkTextFieldXButton.imageset/Frame 59697@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkTextFieldXButton.imageset/Frame 59697@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/DesignSystem/Sources/UIComponents/WKTextField.swift
  Projects/DesignSystem/Sources/UITextField+.swift
  Projects/DesignSystem/Sources/UIView+.swift
  Projects/DesignSystem/Sources/UIViewController+.swift
Labels: 📱 UI, size/m

#18 Feat: WKTextView 컴포넌트 구현
  Projects/DesignSystem/Sources/UIComponents/UIScrollView+.swift
  Projects/DesignSystem/Sources/UIComponents/WKTextView.swift
Labels: 📱 UI, 🚨 help, size/m

#20 Feat: WKDateTextField 구현
  Projects/DesignSystem/Sources/UIComponents/WKDateTextField.swift
  Projects/DesignSystem/Sources/UIComponents/WKTextField.swift
Labels: 📱 UI, size/s

#28 Chore: RxGesture추가
  .package.resolved
  Projects/App/Project.swift
  Projects/DesignSystem/Project.swift
  Projects/Global/Project.swift
  Projects/Global/Sources/Extensions/UIView+Reactive.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✅ chore, size/s

#23 Feat: date button 커스텀
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small.imageset/wk_arrow_small.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small.imageset/wk_arrow_small@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small.imageset/wk_arrow_small@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKDateButton.swift
  Projects/DesignSystem/Sources/UIComponents/exampleComponents.swift
  Projects/Global/Sources/Extensions/Date+.swift
Labels: 📱 UI, size/m

#24 Feat: WKSelectableTextField 구현
  Projects/DesignSystem/Sources/UIComponents/WKDateTextField.swift
  Projects/DesignSystem/Sources/UIComponents/WKSelectableTextField.swift
Labels: 📱 UI, size/s

#34 feat: navigation component 구현
  Projects/App/Sources/Applications/Supports/SceneDelegate.swift
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/DesignSystem/Sources/Extensions/UINavigationController+.swift
  Projects/DesignSystem/Sources/UIComponents/Navigation/WKNavigationBar.swift
  Projects/DesignSystem/Sources/UIComponents/Navigation/WKNavigationButton.swift
  Projects/DesignSystem/Sources/UIComponents/Navigation/WKNavigationController.swift
  Projects/Global/Sources/Extensions/UIImage+.swift
Labels: 📱 UI, size/m
