Repository TEAM-Workit/Workit-iOS, pull requests merged in 2022-12, with the labels that each got.

#36 Chore: 익스텐션 및 폴더링 정리
  Projects/DesignSystem/Sources/UIComponents/Navigations/WKNavigationBar.swift
  Projects/DesignSystem/Sources/UIComponents/Navigations/WKNavigationButton.swift
  Projects/DesignSystem/Sources/UIComponents/Navigations/WKNavigationController.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKDateTextField.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKSelectableTextField.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKTextField.swift
  Projects/DesignSystem/Sources/UIComponents/TextViews/WKTextView.swift
  Projects/DesignSystem/Sources/UIComponents/Toggles/WKToggle.swift
  Projects/Global/Sources/Extensions/Foundation/Date+.swift
  Projects/Global/Sources/Extensions/Reative/UIView+Reactive.swift
  Projects/Global/Sources/Extensions/UIKit/UIImage+.swift
  Projects/Global/Sources/Extensions/UIKit/UIScrollView+.swift
  Projects/Global/Sources/Extensions/UIKit/UITextField+.swift
  Projects/Global/Sources/Extensions/UIKit/UIView+.swift
  Projects/Global/Sources/Extensions/UIKit/UIViewController+.swift
Labels: ✅ chore, size/s

#38 Chore: Domain 모듈 추가
  Projects/App/Project.swift
  Projects/Domain/Project.swift
  Projects/Domain/Resources/DomainResources.swift
  Projects/Domain/Sources/DomainSources.swift
  Projects/Domain/Tests/DomainTests.swift
Labels: ✅ chore, size/s

#32 Feat: WKStarLabel 구현
  Projects/DesignSystem/Sources/UIComponents/WKStarLabel.swift
Labels: 📱 UI, size/s

#30 Feat: WKCapabilityAddButton 구현
  Projects/DesignSystem/Resources/Assets.xcassets/wkCapabilityPlus.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wkCapabilityPlus.imageset/Frame 59601.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkCapabilityPlus.imageset/Frame 59601@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkCapabilityPlus.imageset/Frame 59601@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKCapabilityAddButton.swift
Labels: 📱 UI, size/s

#41 Chore: WKSelectableTextField → WKTextFieldStyleButton으로 변경
  Projects/App/Sources/Global/Extensions/UIButton+.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKTextFieldStyleButton.swift
  Projects/DesignSystem/Sources/UIComponents/Labels/WKStarLabel.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKDateTextField.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKSelectableTextField.swift
Labels: 📱 UI, ✅ chore, size/m

#45 Feat: WKPageTab 구현
  Projects/DesignSystem/Sources/UIComponents/PageTab/WKPageButton.swift
  Projects/DesignSystem/Sources/UIComponents/PageTab/WKPageTab.swift
  Projects/Global/Sources/Extensions/UIKit/UIStackView+.swift
Labels: 📱 UI, size/m

#44 Feat: WKRoundedButton 컴포넌트 구현
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKRoundedButton.swift
  Projects/Global/Sources/Extensions/UIKit/UIButton+.swift
Labels: 📱 UI, size/s

#50 Fix: Date Extension, Type 수정 (#33)
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKDateButton.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKTextFieldStyleButton.swift
  Projects/Global/Sources/Extensions/Foundation/Date+.swift
Labels: 🐞 bug & fix, size/s

#47 Feat: Project CollectionView Cell
  Projects/DesignSystem/Sources/Base/Labels/PaddingLabel.swift
  Projects/DesignSystem/Sources/Extensions/UIColor+.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKProjectCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/Labels/WKTagLabel.swift
  Projects/Global/Sources/Enums/TagType.swift
  Projects/Global/Sources/GlobalSourcesExample.swift
Labels: 📱 UI, size/m

#54 Feat: WriteViewController UI 구현
  Projects/App/Sources/Global/Base/BaseViewController.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKAbilityAddButton.swift
  Projects/DesignSystem/Sources/UIComponents/Labels/WKStarLabel.swift
  Projects/DesignSystem/Sources/UIComponents/TextViews/WKTextView.swift
Labels: 📱 UI, size/m

#55 Feat: login view controller UI
  Projects/App/Sources/Screens/Login/LoginReactor.swift
  Projects/App/Sources/Screens/Login/LoginViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/imgWorkitTextLogo.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/imgWorkitTextLogo@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/imgWorkitTextLogo@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/Global/Sources/Extensions/UIKit/UILabel+.swift
Labels: 📱 UI, size/m

#57 Chore: add Calendar third party library
  .package.resolved
  Projects/App/Project.swift
  Projects/DesignSystem/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✅ chore, size/s
