Repository TEAM-Workit/Workit-iOS, pull requests merged in 2023-06, with the labels that each got.

#175 Mixpanel-User Properties
  Projects/App/Sources/Applications/Supports/AppDelegate.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
Labels: ✅ chore, size/s

#180 Fix: 기록하기 시 시간 잘못 들어가는 버그 수정
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKTextFieldStyleButton.swift
Labels: 🐞 bug & fix, size/xs

#181 Feat: 홈, 온보딩 Mixpanel 로깅
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Onboarding/OnboardingReactor.swift
Labels: ✅ chore, size/xs

#183 Fix: QA 반영 및 믹스패널 로깅 추가
  Projects/App/Sources/Global/Extensions/UIViewController+.swift
  Projects/App/Sources/Screens/Library/AbilityViewController.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementReactor.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementViewController.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Setting/Views/SettingTableViewCell.swift
  Projects/App/Sources/Screens/Splash/SplashViewController.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Toggles/WKToggle.swift
Labels: 🐞 bug & fix, size/m

#185 Chore: 다크모드 비활성화
  Projects/App/Plists/Info.plist
Labels: ✅ chore

#187 fix: chane home emptyview title (#186)
  Projects/App/Sources/Screens/Home/HomeReactor.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Home/Views/HomeEmptyView.swift
Labels: 🐞 bug & fix, size/s

#189 feat: add home date Button today text (#188)
  Projects/App/Sources/Screens/Home/Views/MyWorkitHeaderView.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKDateButton.swift
Labels: 📱 UI, size/s
