Repository TEAM-Workit/Workit-iOS, pull requests merged in 2023-05, with the labels that each got.

#134 Chore: 애플 로그인, APN 세팅
  Projects/App/App.entitlements
  Projects/App/Plists/Info.plist
  Projects/App/Sources/Screens/Login/LoginViewController.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✅ chore, size/s

#140 Feat: setting view 작업
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementViewController.swift
  Projects/App/Sources/Screens/Setting/SettingReactor.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Setting/Views/UserProfileView.swift
  Projects/Data/Sources/Network/User/UserRouter.swift
  Projects/Data/Sources/Network/User/UserService.swift
  Projects/Data/Sources/Repositories/DefaultUserRepository.swift
  Projects/Data/Sources/ResponseDTO/UserInformationResponseDTO.swift
  Projects/DesignSystem/Sources/UIComponents/Navigations/WKNavigationBar.swift
  Projects/Domain/Sources/Entities/User.swift
  Projects/Domain/Sources/Interfaces/UserRepository.swift
  Projects/Domain/Sources/UseCases/UserUseCase.swift
Labels: 📡 network, size/m

#142 Feat: connect server withdraw (#110)
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalReactor.swift
  Projects/Data/Sources/Network/User/UserRouter.swift
  Projects/Data/Sources/Network/User/UserService.swift
  Projects/Data/Sources/Repositories/DefaultUserRepository.swift
  Projects/Data/Sources/Utils/ResponseType/BaseResponseType.swift
  Projects/Domain/Sources/Interfaces/UserRepository.swift
  Projects/Domain/Sources/UseCases/UserUseCase.swift
Labels: size/s

#143 Feat: 오억년만에 탭바 달음 (#46)
  Projects/App/Sources/Global/Utils/RootViewChange.swift
  Projects/App/Sources/Screens/Library/LibraryViewController.swift
  Projects/App/Sources/Screens/MainTab/MainTabbarController.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/wk_write.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_write.imageset/wk_write.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_write.imageset/wk_write@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_write.imageset/wk_write@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/DesignSystem/Sources/Extensions/UIFont+.swift
  Projects/DesignSystem/Sources/UIComponents/Tabbar/WKTabbar.swift
  Projects/DesignSystem/Sources/UIComponents/Tabbar/WKTabbarController.swift
  Projects/DesignSystem/Sources/UIComponents/Tabbar/WKTabbarItem.swift
Labels: 📱 UI, size/m

#146 Feat: 홈에서 워킷 선택 시 워킷 상세보기로 이동 (#145)
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
Labels: size/s

#148 Feat: connect link login term (#144)
  Projects/App/Sources/Screens/Login/LoginViewController.swift
  Projects/Global/Sources/Extensions/Foundation/NSRange+.swift
  Projects/Global/Sources/Extensions/Foundation/String+.swift
  Projects/Global/Sources/Extensions/UIKit/UILabel+.swift
Labels: size/s

#150 fix: viewDidLoad -> viewWillApeear (#147)
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/App/Sources/Screens/Library/ProjectReactor.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
Labels: size/s

#157 Chore: 기록하기 - 역량 태그 선택되어 있던 내용 유지하도록 구현
  Projects/App/Sources/Screens/Write/PickAbility/PickAbilityBottomViewController.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
Labels: 🛠 QA, ✅ chore, size/s

#158 Chore: 워킷 상세보기 업무 내용 없는 경우 가이드 텍스트 수정
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
  Projects/DesignSystem/Sources/UIComponents/TextViews/WKTextView.swift
Labels: 🛠 QA, ✅ chore, size/s

#160 Fix: 기록하기 날짜 설정 바텀시트 관련 QA 요구사항 반영
  Projects/App/Sources/Screens/CalendarBottomSheet/SingleDayCalendarBottomSheetViewController.swift
Labels: 🛠 QA, ✅ chore, size/s

#162 Fix: 기록하기 저장 버튼 터치 중복 막기
  Projects/App/Sources/Screens/Write/WriteViewController.swift
Labels: 🐞 bug & fix, 🛠 QA, size/xs

#164 Fix: 기록하기 TextView Tint color 변경
  Projects/DesignSystem/Sources/UIComponents/TextViews/WKTextView.swift
Labels: 🛠 QA, ✅ chore, size/xs

#166 Fix: QA p1
  Projects/App/Sources/Screens/CalendarBottomSheet/CalendarBottomSheetViewController.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Home/Views/HomeEmptyView.swift
  Projects/App/Sources/Screens/Login/LoginViewController.swift
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalReasonView.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKProjectCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/Labels/WKTagLabel.swift
  Projects/Global/Sources/Extensions/UIKit/UILabel+.swift
Labels: 🛠 QA, size/m

#168 Chore: add mixpanel dependency (#167)
  Projects/App/Project.swift
  Tuist/Dependencies.swift
Labels: size/xs

#169 Fix: 탈퇴 사유 관련 로직 수정 (#155)
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalReasonView.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalReactor.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalViewController.swift
Labels: 🛠 QA

#170 Fix: 온보딩 레이아웃, 행간 조절 (#155)
  Projects/App/Sources/Screens/Onboarding/Views/OnboardingCollectionViewCell.swift
Labels: 🛠 QA, size/s

#165 Fix: 1차 QA 반영
  Projects/App/Sources/Screens/Library/AbilityReactor.swift
  Projects/App/Sources/Screens/Library/AbilityViewController.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementReactor.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementViewController.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectCreateView.swift
  Projects/Data/Sources/Repositories/DefaultProjectRepository.swift
  Projects/Domain/Sources/Interfaces/ProjectRepository.swift
  Projects/Domain/Sources/UseCases/ProjectUseCase.swift
Labels: 🛠 QA, ✅ chore, size/m

#173 fix: change logo asset (#155)
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/imgWorkitTextLogo.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/imgWorkitTextLogo@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgWorkitTextLogo.imageset/imgWorkitTextLogo@3x.png
Labels: 🛠 QA, size/xs

#174 Feat: 최소버전 강제 업데이트 추가 (#172)
  Projects/App/Plists/Info.plist
  Projects/App/Project.swift
  Projects/App/Sources/Applications/External/Firebase/FirebaseService.swift
  Projects/App/Sources/Applications/Supports/AppDelegate.swift
  Projects/App/Sources/Global/Extensions/UIViewController+.swift
  Projects/App/Sources/Screens/Splash/SplashViewController.swift
Labels: ✅ chore, size/m
