Repository TEAM-Workit/Workit-iOS, pull requests merged in 2023-04, with the labels that each got.

#95 Fix: fix home dateButton bug (#94)
  Projects/App/Sources/Screens/CalendarBottomSheet/CalendarBottomSheetViewController.swift
  Projects/App/Sources/Screens/Home/HomeReactor.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Home/Views/MyWorkitHeaderView.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKDateButton.swift
Labels: 🐞 bug & fix, size/s

#96 Chore: 기록하기 캘린더 바텀시트 구현 및 취소 구현
  Projects/App/Sources/Screens/CalendarBottomSheet/CalendarBottomSheetViewController.swift
  Projects/App/Sources/Screens/CalendarBottomSheet/SingleDayCalendarBottomSheetViewController.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKTextFieldStyleButton.swift
Labels: 📱 UI, size/m

#100 Fix: change HorizonCalendar tuist dependencies + spm (#98)
  .package.resolved
  Projects/App/Project.swift
  Projects/App/Sources/Screens/CalendarBottomSheet/CalendarBottomSheetViewController.swift
  Projects/DesignSystem/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🐞 bug & fix, size/s

#99 Feat: 워킷 상세보기 UI 구현
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Resources/Font/Pretendard-Bold.ttf
  Projects/DesignSystem/Resources/Font/Pretendard-Medium.ttf
  Projects/DesignSystem/Resources/Font/Pretendard-Regular.ttf
  Projects/DesignSystem/Resources/Font/Pretendard-SemiBold.ttf
  Projects/DesignSystem/Resources/Font/SUIT-Bold.ttf
  Projects/DesignSystem/Resources/Font/SUIT-Medium.ttf
  Projects/DesignSystem/Resources/Font/SUIT-Regular.ttf
  Projects/DesignSystem/Resources/Font/SUIT-SemiBold.ttf
  Projects/DesignSystem/Sources/Extensions/UIFont+.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKWriteAbilityCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/TextViews/WKTextView.swift
  Projects/Global/Sources/Extensions/Foundation/Date+.swift
Labels: 📱 UI, size/l

#103 Feat: 프로젝트 관리 페이지 서버 연결
  Projects/App/Sources/Global/Utils/Alert/AlertActionType.swift
  Projects/App/Sources/Global/Utils/Alert/AlertController.swift
  Projects/App/Sources/Global/Utils/Alert/AlertReactor.swift
  Projects/App/Sources/Screens/Setting/Alert/ProjectDeleteAlertAction.swift
  Projects/App/Sources/Screens/Setting/Alert/ProjectDeleteAlertReactor.swift
  Projects/App/Sources/Screens/Setting/Alert/ProjectManagementAlertAction.swift
  Projects/App/Sources/Screens/Setting/Alert/ProjectManagementAlertReactor.swift
  Projects/App/Sources/Screens/Setting/ProjectCreateViewController.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementReactor.swift
  Projects/App/Sources/Screens/Setting/ProjectManagementViewController.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectCreateView.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectHeaderReusableView.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectListCollectionViewCell.swift
  Projects/Data/Sources/Network/Collection/CollectionRouter.swift
  Projects/Data/Sources/Network/Collection/CollectionService.swift
  Projects/Data/Sources/Network/NetworkService.swift
  Projects/Data/Sources/Network/Project/ProjectRouter.swift
  Projects/Data/Sources/Network/Project/ProjectService.swift
  Projects/Data/Sources/Repositories/DefaultCollectionRepository.swift
  Projects/Data/Sources/Repositories/DefaultProjectRepository.swift
  Projects/Data/Sources/RequestDTO/ProjectRequestDTO.swift
  Projects/Data/Sources/ResponseDTO/ProjectResponseDTO.swift
  Projects/Domain/Sources/Entities/Project.swift
  Projects/Domain/Sources/Interfaces/ProjectRepository.swift
  Projects/Domain/Sources/UseCases/ProjectUseCase.swift
Labels: 📡 network, size/xl

#105 Chore: 워킷 상세보기 서버 연결
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
  Projects/Data/Sources/Network/Work/WorkRouter.swift
  Projects/Data/Sources/Network/Work/WorkService.swift
  Projects/Data/Sources/Repositories/DefaultWorkRepository.swift
  Projects/Data/Sources/ResponseDTO/WorkResponseDTO.swift
  Projects/Domain/Sources/Entities/WorkDetail.swift
  Projects/Domain/Sources/Interfaces/WorkRepository.swift
  Projects/Global/Sources/Extensions/Foundation/Date+.swift
Labels: 📡 network, size/m

#108 Chore: 워킷 상세보기 workId 프로퍼티 구현
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
Labels: ✅ chore, size/s

#109 Feat: 탈퇴뷰 UI
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalBottomView.swift
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalReasonView.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalReactor.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/wk_check.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_check.imageset/wk_check.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_check.imageset/wk_check@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_check.imageset/wk_check@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_uncheck.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_uncheck.imageset/wk_uncheck.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_uncheck.imageset/wk_uncheck@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_uncheck.imageset/wk_uncheck@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
Labels: 📱 UI, size/l

#112 Feat: 카카오 로그인
  .package.resolved
  Projects/App/Plists/Info.plist
  Projects/App/Project.swift
  Projects/App/Sources/Applications/Supports/AppDelegate.swift
  Projects/App/Sources/Applications/Supports/SceneDelegate.swift
  Projects/App/Sources/Screens/Login/LoginViewController.swift
  Projects/Data/Project.swift
  Projects/DesignSystem/Project.swift
  Projects/Domain/Project.swift
  Projects/Domain/Sources/Entities/AuthToken.swift
  Projects/Domain/Sources/UseCases/AuthUseCase.swift
  Projects/Global/Project.swift
  Projects/Global/Sources/Utils/UserDefaultsManager.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 📡 network, size/m

#115 Feat: 기록하기 - 프로젝트, 역량 선택 바텀시트 api 연결
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
  Projects/App/Sources/Screens/Write/PickAbility/PickAbilityBottomViewController.swift
  Projects/App/Sources/Screens/Write/PickAbility/SelectAbilityTableViewCell.swift
  Projects/App/Sources/Screens/Write/SelectProject/SelectProjectBottomViewController.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/Data/Sources/Network/Ability/AbilityRouter.swift
  Projects/Data/Sources/Network/Ability/AbilityService.swift
  Projects/Data/Sources/Network/NetworkService.swift
  Projects/Data/Sources/Network/Project/ProjectRouter.swift
  Projects/Data/Sources/Network/Project/ProjectService.swift
  Projects/Data/Sources/Repositories/DefaultAbilityRepository.swift
  Projects/Data/Sources/Repositories/DefaultProjectRepository.swift
  Projects/Data/Sources/ResponseDTO/AllAbilityResponseDTO.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKWriteAbilityCollectionViewCell.swift
  Projects/Domain/Sources/Interfaces/AbilityRepository.swift
  Projects/Domain/Sources/Interfaces/ProjectRepository.swift
Labels: 📡 network, size/m

#118 Feat: 워킷 수정하기/삭제하기 api 연결
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/Data/Sources/Network/Work/WorkRouter.swift
  Projects/Data/Sources/Network/Work/WorkService.swift
  Projects/Data/Sources/Repositories/DefaultWorkRepository.swift
  Projects/Data/Sources/ResponseDTO/WorkResponseDTO.swift
  Projects/Domain/Sources/Interfaces/WorkRepository.swift
Labels: 📡 network, size/m

#120 Fix: 역량태그 선택 해제 시 에러 처리
  Projects/App/Sources/Screens/Write/PickAbility/PickAbilityBottomViewController.swift
Labels: 🐞 bug & fix, size/xs

#122 Chore: 업무명 50자 이상 입력 시 키보드 비활성화
  Projects/App/Sources/Screens/Write/WriteViewController.swift
Labels: ✅ chore, size/xs

#125 Chore: 앱 아이콘 설정
  Projects/App/Resources/AppIcon.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/AppIcon.xcassets/AppIcon.appiconset/wk_logo.png
  Projects/App/Resources/AppIcon.xcassets/Contents.json
Labels: ✅ chore

#111 Feat: 프로젝트 모아보기 상세 조회 서버 연결
  Projects/App/Sources/Screens/CalendarBottomSheet/CalendarBottomSheetViewController.swift
  Projects/App/Sources/Screens/CalendarBottomSheet/Views/CalendarBottomSheetTopView.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Library/DetailReactor.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
  Projects/Data/Sources/Network/Project/ProjectRouter.swift
  Projects/Data/Sources/Network/Project/ProjectService.swift
  Projects/Data/Sources/Repositories/DefaultProjectRepository.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKDateButton.swift
  Projects/DesignSystem/Sources/UIComponents/EmptyView/WKEmptyView.swift
  Projects/Domain/Sources/Interfaces/ProjectRepository.swift
  Projects/Domain/Sources/UseCases/ProjectUseCase.swift
  Projects/Global/Sources/Extensions/Foundation/Date+.swift
Labels: 📡 network, size/m

#128 Feat: token 처리
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/Applications/Supports/SceneDelegate.swift
  Projects/App/Sources/Global/Utils/RootViewChange.swift
  Projects/App/Sources/Global/Utils/exampleUtil.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Login/LoginViewController.swift
  Projects/App/Sources/Screens/Onboarding/OnboardingReactor.swift
  Projects/App/Sources/Screens/Onboarding/OnboardingViewController.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Splash/SplashViewController.swift
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalBottomView.swift
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalReasonView.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalReactor.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalViewController.swift
  Projects/Data/Sources/Utils/BaseRequestConvertible.swift
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashLogo.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashLogo.imageset/imgSplashLogo.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashLogo.imageset/imgSplashLogo@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashLogo.imageset/imgSplashLogo@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashTextLogo.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashTextLogo.imageset/imgSplashTextLogo.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashTextLogo.imageset/imgSplashTextLogo@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/imgSplashTextLogo.imageset/imgSplashTextLogo@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
Labels: size/m

#130 fix: fix withdraw button enable logic (#113)
  Projects/App/Sources/Screens/Withdrawal/Views/WithdrawalReasonView.swift
Labels: size/xs

#132 Feat: home empty view
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Home/Views/HomeEmptyView.swift
  Projects/App/Sources/Screens/Withdrawal/WithdrawalViewController.swift
Labels: size/s

#135 Feat: 역량으로 모아보기 상세 서버 연결
  Projects/App/Sources/Global/CommonLayout/ListLayout.swift
  Projects/App/Sources/Screens/Library/AbilityViewController.swift
  Projects/App/Sources/Screens/Library/DetailReactor.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
  Projects/Data/Sources/Network/Ability/AbilityRouter.swift
  Projects/Data/Sources/Network/Ability/AbilityService.swift
  Projects/Data/Sources/Repositories/DefaultAbilityRepository.swift
  Projects/Data/Sources/ResponseDTO/AbilityDetailResponseDTO.swift
  Projects/Domain/Sources/Entities/AbilityDetail.swift
  Projects/Domain/Sources/Interfaces/AbilityRepository.swift
  Projects/Domain/Sources/UseCases/AbilityUseCase.swift
Labels: 📡 network, size/m

#138 Fix: 워킷 상세보기 navi 버그 수정
  Projects/App/Sources/Screens/WorkDetail/WorkDetailViewController.swift
Labels: 🐞 bug & fix, size/s

#139 Chore: 업무 내용 글자 수 카운트 구현
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/Global/Sources/Extensions/UIKit/UILabel+.swift
Labels: 📱 UI, ✅ chore, size/s
