Repository TEAM-Workit/Workit-iOS, pull requests merged in 2023-01, with the labels that each got.

#59 Feat: PickDateBottomViewController 컴포넌트 구현
  Projects/App/Sources/Global/Extensions/UIButton+.swift
  Projects/DesignSystem/Sources/UIComponents/ViewControllers/WKPickDateBottomViewController.swift
  Projects/Global/Sources/Extensions/UIKit/UIButton+.swift
Labels: 📱 UI, size/m

#58 Feat: home UI
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Home/Views/HomeBannerView.swift
  Projects/App/Sources/Screens/Home/Views/MyWorkitHeaderView.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKEmptyCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKProjectCollectionViewCell.swift
  Projects/Global/Sources/Extensions/UIKit/UICollectionView+.swift
  Projects/Global/Sources/Utils/ClassName.swift
Labels: 📱 UI, size/l

#64 Chore: add RxAlamofire (#63)
  .package.resolved
  Projects/App/Project.swift
  Projects/Data/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✅ chore, size/s

#62 Feat: onboarding (#61)
  Projects/App/Sources/Global/Extensions/UIViewController+.swift
  Projects/App/Sources/Screens/Onboarding/Models/Onboarding.swift
  Projects/App/Sources/Screens/Onboarding/OnboardingReactor.swift
  Projects/App/Sources/Screens/Onboarding/OnboardingViewController.swift
  Projects/App/Sources/Screens/Onboarding/Views/OnboardingCollectionViewCell.swift
  Projects/App/Sources/Screens/Onboarding/Views/WKPageControl.swift
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding1.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding1.imageset/wk_onboarding1.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding1.imageset/wk_onboarding1@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding1.imageset/wk_onboarding1@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding2.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding2.imageset/wk_onboarding2.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding2.imageset/wk_onboarding2@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding2.imageset/wk_onboarding2@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding3.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding3.imageset/wk_onboarding3.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding3.imageset/wk_onboarding3@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_onboarding3.imageset/wk_onboarding3@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
Labels: 📱 UI, size/l

#69 Feat: setting view (#68)
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Setting/Views/SettingTableViewCell.swift
  Projects/App/Sources/Screens/Setting/Views/UserProfileView.swift
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small_next.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small_next.imageset/wk_arrow_small.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small_next.imageset/wk_arrow_small@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wk_arrow_small_next.imageset/wk_arrow_small@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/Global/Sources/Extensions/UIKit/UITableView+.swift
Labels: 📱 UI, size/m

#67 Feat: 모아보기 뷰 UI (#65)
  Projects/App/Sources/Global/CommonLayout/ListLayout.swift
  Projects/App/Sources/Screens/Library/AbilityViewController.swift
  Projects/App/Sources/Screens/Library/LibraryCollectionViewCell.swift
  Projects/App/Sources/Screens/Library/LibraryViewController.swift
  Projects/App/Sources/Screens/Library/ListCollectionView.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKProjectCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/Labels/WKTagLabel.swift
Labels: 📱 UI, size/m

#73 Feat: 모아보기 상세 구현
  Projects/App/Sources/Global/CommonLayout/ListLayout.swift
  Projects/App/Sources/Screens/Library/AbilityViewController.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/App/Sources/Screens/Library/ListCollectionView.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
Labels: 📱 UI, size/m

#74 Feat: network setting
  .gitignore
  Projects/Data/Plists/Info.plist
  Projects/Data/Project.swift
  Projects/Data/Sources/Network/Auth/AuthRouter.swift
  Projects/Data/Sources/Network/Auth/AuthService.swift
  Projects/Data/Sources/Network/NetworkService.swift
  Projects/Data/Sources/Repositories/DefaultAuthRepository.swift
  Projects/Data/Sources/RequestDTO/AuthRequestDTO.swift
  Projects/Data/Sources/ResponseDTO/AuthResponseDTO.swift
  Projects/Data/Sources/URLConstant.swift
  Projects/Data/Sources/Utils/BaseRequestConvertible.swift
  Projects/Data/Sources/Utils/ExpectingObject.swift
  Projects/Data/Sources/Utils/Extensions/Encodable+.swift
  Projects/Data/Sources/Utils/HTTPError.swift
  Projects/Data/Sources/Utils/JsonConverter.swift
  Projects/Data/Sources/Utils/ResponseType/BaseArrayResponseType.swift
  Projects/Data/Sources/Utils/ResponseType/BaseResponseType.swift
  Projects/Data/Sources/Utils/ResponseType/StatusCase.swift
  Projects/Data/Sources/exampleSource.swift
  Projects/Domain/Project.swift
  Projects/Domain/Sources/DomainSources.swift
  Projects/Domain/Sources/Entities/AuthToken.swift
  Projects/Domain/Sources/Interfaces/AuthRepository.swift
  Projects/Domain/Sources/UseCases/AuthUseCase.swift
  Projects/Global/Sources/Enums/SocialType.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 📡 network, size/l

#70 Feat: PickAbilityBottomViewController 구현 #60
  Projects/App/Sources/Screens/Write/Entities/WriteAbility.swift
  Projects/App/Sources/Screens/Write/PickAbilityBottomViewController.swift
  Projects/App/Sources/Screens/Write/SelectAbilityTableViewCell.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChooseCheck.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChooseCheck.imageset/Frame 59600.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChooseCheck.imageset/Frame 59600@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChooseCheck.imageset/Frame 59600@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChoosePlus.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChoosePlus.imageset/Frame 59601.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChoosePlus.imageset/Frame 59601@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/wkSkillChoosePlus.imageset/Frame 59601@3x.png
  Projects/DesignSystem/Sources/Constants/Image.swift
  Projects/Global/Sources/Extensions/UIKit/UITableView+.swift
  Projects/Global/Sources/Extensions/UIKit/UIView+.swift
Labels: 📱 UI, size/l

#80 Feat: 기록하기 AbilityCollectionView 구현 #53
  Projects/App/Sources/Screens/Write/Entities/WriteAbility.swift
  Projects/App/Sources/Screens/Write/PickAbility/PickAbilityBottomViewController.swift
  Projects/App/Sources/Screens/Write/PickAbility/SelectAbilityTableViewCell.swift
  Projects/App/Sources/Screens/Write/WriteAbilityCollectionViewFlowLayout.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKWriteAbilityCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/CollectionViews/WKWriteAbilityCollectionView.swift
Labels: 📱 UI, size/m

#83 Feat: 홈뷰 서버연결 (#78)
  Projects/App/Sources/Screens/Home/HomeReactor.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/App/Sources/Screens/Library/DetailViewController.swift
  Projects/Data/Sources/Network/NetworkService.swift
  Projects/Data/Sources/Network/Work/WorkRouter.swift
  Projects/Data/Sources/Network/Work/WorkService.swift
  Projects/Data/Sources/Repositories/DefaultWorkRepository.swift
  Projects/Data/Sources/ResponseDTO/WorkResponseDTO.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKProjectCollectionViewCell.swift
  Projects/Domain/Sources/Entities/Ability.swift
  Projects/Domain/Sources/Entities/Project.swift
  Projects/Domain/Sources/Entities/Work.swift
  Projects/Domain/Sources/Interfaces/WorkRepository.swift
  Projects/Domain/Sources/UseCases/WorkUseCase.swift
  Projects/Global/Sources/Enums/TagType.swift
  Projects/Global/Sources/Extensions/Foundation/Date+.swift
Labels: 📡 network, size/m

#75 Feat: project create view
  Projects/App/Sources/Screens/Setting/ProjectCreateViewController.swift
  Projects/App/Sources/Screens/Setting/SettingViewController.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectCreateCollectionViewCell.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectHeaderReusableView.swift
  Projects/App/Sources/Screens/Setting/Views/ProjectListCollectionViewCell.swift
Labels: 📱 UI, size/m

#82 Feat: SelectProjectBottomViewController - Project Select구현 #81
  Projects/App/Sources/Screens/Write/SelectProject/SelectProjectBottomViewController.swift
  Projects/App/Sources/Screens/Write/WriteLeftAlignedCollectionViewFlowLayout.swift
  Projects/App/Sources/Screens/Write/WriteViewController.swift
  Projects/DesignSystem/Sources/UIComponents/Buttons/WKTextFieldStyleButton.swift
  Projects/DesignSystem/Sources/UIComponents/Cells/WKWriteRecentProjectCollectionViewCell.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKProjectSearchTextField.swift
  Projects/DesignSystem/Sources/UIComponents/TextFields/WKTextField.swift
Labels: 📱 UI

#85 Feat: library network
  Projects/App/.swiftlint.yml
  Projects/App/Sources/Screens/Library/AbilityReactor.swift
  Projects/App/Sources/Screens/Library/AbilityViewController.swift
  Projects/App/Sources/Screens/Library/LibraryViewController.swift
  Projects/App/Sources/Screens/Library/ProjectReactor.swift
  Projects/App/Sources/Screens/Library/ProjectViewController.swift
  Projects/App/Sources/Screens/Library/Views/LibraryCollectionViewCell.swift
  Projects/App/Sources/Screens/Library/Views/ListCollectionView.swift
  Projects/Data/.swiftlint.yml
  Projects/Data/Sources/Network/Auth/CollectionRouter.swift
  Projects/Data/Sources/Network/Auth/CollectionService.swift
  Projects/Data/Sources/Network/NetworkService.swift
  Projects/Data/Sources/Repositories/DefaultCollectionRepository.swift
  Projects/Data/Sources/ResponseDTO/AbilityResponseDTO.swift
  Projects/Data/Sources/ResponseDTO/ProjectResponseDTO.swift
  Projects/Data/Sources/Utils/ResponseType/BaseArrayResponseType.swift
  Projects/DesignSystem/.swiftlint.yml
  Projects/Domain/.swiftlint.yml
  Projects/Domain/Sources/Entities/LibraryItem.swift
  Projects/Domain/Sources/Interfaces/CollectionRepository.swift
  Projects/Domain/Sources/UseCases/CollectionUseCase.swift
Labels: 📡 network, size/l

#87 Feat: home username 받아오기 서버연결
  Projects/App/Sources/Screens/Home/HomeReactor.swift
  Projects/App/Sources/Screens/Home/HomeViewController.swift
  Projects/Data/Sources/Network/NetworkService.swift
  Projects/Data/Sources/Network/User/UserRouter.swift
  Projects/Data/Sources/Network/User/UserService.swift
  Projects/Data/Sources/Repositories/DefaultUserRepository.swift
  Projects/Data/Sources/ResponseDTO/UserNicknameResponseDTO.swift
  Projects/Domain/Sources/Entities/User.swift
  Projects/Domain/Sources/Interfaces/UserRepository.swift
  Projects/Domain/Sources/UseCases/UserUseCase.swift
Labels: 📡 network, size/m
